calendar_app/urls.py
from django.urls import path
from . import views
from .views import detail, create, calendar, delete, update,get_events


app_name = "cal"
urlpatterns = [
    path("calendar/", views.calendar, name='calendar'),
    path('detail/<int:pk>', detail.as_view(), name='detail'),
    path('create/', create.as_view(), name='create'),
    path('delete/<int:pk>', delete.as_view(), name='delete'),
    path('update/<int:pk>', update.as_view(), name='update'),
    path('get-events/', views.get_events, name='get_events'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include ,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calendar_app.urls')),
]

calendar_app/models.py
from django.db import models

# Create your models here.

CHOICE = (('primary','完了'),('warning','着手'),('danger','未着手'),('dark','期限切れ'))

class TodoModel(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField()
    priority = models.CharField(
        max_length=50,
        choices = CHOICE
        )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    
    
    def __str__(self):
        return self.title

calendar_app/forms.py
from django import forms
from .models import TodoModel

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoModel
        fields = ['title', 'memo','priority', 'start_date','end_date']
        widgets = {
            'start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

calendar_app/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.template import loader
from django.http import HttpResponse

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView,View
from django.urls import reverse_lazy,reverse

from .models import TodoModel
from .forms import TodoForm

from django.http import JsonResponse

from django.utils import timezone

#ログイン機能
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required #ログイン機能

def calendar(request):
    todolists = TodoModel.objects.all()
    context = {
        'todolists': todolists,
    }
    # template = loader.get_template("calendar_app/calendar.html")
    # return HttpResponse(template.render())
    return render(request, 'calendar_app/calendar.html', context)
    
class detail(DetailView):
    template_name = 'calendar_app/detail.html'
    model = TodoModel
    
class create(CreateView):
    template_name = 'calendar_app/create.html'
    model = TodoModel
    form_class = TodoForm
    success_url = reverse_lazy('cal:calendar')
    # リアルタイムを表示する方法
    # def get_initial(self):
    #     initial = super().get_initial()
    #     initial['start_date'] = timezone.now()
    #     initial['end_date'] = timezone.now()
    #     return initial

class delete(DeleteView):
    template_name = 'calendar_app/delete.html'
    model = TodoModel
    success_url = reverse_lazy('cal:calendar')
    
class update(UpdateView):
    template_name = 'calendar_app/update.html'
    model = TodoModel
    form_class = TodoForm
    # fields = ('title', 'memo', 'priority', 'start_date', 'end_date')
    success_url = reverse_lazy('cal:calendar')
    
    
def get_events(request):
    events = TodoModel.objects.all()
    event_data = []

    for event in events:
        event_data.append({
            'id': event.id,
            'title': event.title,
            'memo': event.memo,
            'start': event.start_date.isoformat(),
            'end': event.end_date.isoformat(),
            'status': event.priority,
        })

    return JsonResponse(event_data, safe=False)

taskTool/views.py
from django.shortcuts import render

# Create your views here.

templates/calendar_app/calendar.html
{% load static %}
{% load django_bootstrap5 %}<!-- カスタムテンプレートタグの読み込み -->

<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'calendar/style.css' %}">
  <script src="{% static 'calendar/app.js' %}"></script>
  {% bootstrap_css %}<!-- BootstrapのCSSの読み込み -->
  {% bootstrap_javascript %}<!-- JavaScriptの読み込み -->
 
</head>

<body>
  <h1>課題管理アプリ</h1>
  <div class="container-fluid">
    <div class="row">
      <div class="col-9 ">
        <div id='calendar'></div>
      </div>
      
      <div class="col-3">
        <h3>達成状況</h3>
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>完了⚪︎</th>
            </tr>
          </thead>
          {% for item in todolists %}
            {% if item.priority == "primary" %}
              <tbody>
                <tr>
                  <td>
                    <div class="alert alert-{{ item.priority }}" role ="alert">
                      <p>{{ item.title }}</p>
                      <div>
                        <a href="{% url 'cal:detail' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
                        <a href="{% url 'cal:update' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">編集</a>
                        <a href="{% url 'cal:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
                      </div>
                      <br>
                      <p>期日：{{ item.end_date  | date:"o/n/j" }}</p>
                    </div>
                  </td>
                </tr>
              </tbody>
            {% endif %}
          {% endfor %}
        </table>
        
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>着手△</th>
            </tr>
          </thead>
          {% for item in todolists %}
            {% if item.priority == "warning" %}
              <tbody>
                <tr>
                  <td>
                    <div class="alert alert-{{ item.priority }}" role ="alert">
                      <p>{{ item.title }}</p>
                      <div>
                        <a href="{% url 'cal:detail' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
                        <a href="{% url 'cal:update' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">編集</a>
                        <a href="{% url 'cal:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
                      </div>
                      <br>
                      <p>期日：{{ item.end_date  | date:"o/n/j" }}</p>
                    </div>
                  </td>
                </tr>
              </tbody>
            {% endif %}
          {% endfor %}
        </table>
        
         <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>未着手×</th>
            </tr>
          </thead>
          {% for item in todolists %}
            {% if item.priority == "danger" %}
              <tbody>
                <tr>
                  <td>
                    <div class="alert alert-{{ item.priority }}" role ="alert">
                      <p>{{ item.title }}</p>
                      <div>
                        <a href="{% url 'cal:detail' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
                        <a href="{% url 'cal:update' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">編集</a>
                        <a href="{% url 'cal:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
                      </div>
                      <br>
                      <p>期日：{{ item.end_date   | date:"o/n/j" }}</p>
                    </div>
                  </td>
                </tr>
              </tbody>
            {% endif %}
          {% endfor %}
        </table>
        
         <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>期限切れ</th>
            </tr>
          </thead>
          {% for item in todolists %}
            {% if item.priority == "dark" %}
              <tbody>
                <tr>
                  <td>
                    <div class="alert alert-{{ item.priority }}" role ="alert">
                      <p>{{ item.title }}</p>
                      <div>
                        <a href="{% url 'cal:detail' item.pk %}" class="btn btn-primary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
                        <a href="{% url 'cal:update' item.pk %}" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">編集</a>
                        <a href="{% url 'cal:delete' item.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a>
                      </div>
                      <br>
                      <p>期日：{{ item.end_date   | date:"o/n/j" }}</p>
                    </div>
                  </td>
                </tr>
              </tbody>
            {% endif %}
          {% endfor %}
        </table>
        <a href="{% url 'cal:create' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">新規作成</a>
        
      </div>
      
    </div>
  </div>
  {% block content %}
  {% endblock %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">
  <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>
</body>
</html>

templates/calendar_app/create.html
<form action = '{% url 'cal:create' %}' method = 'POST'>
    {% csrf_token %}
    <p>タイトル：{{ form.title }}</p>
    <p>詳細：</p>
    <p>{{ form.memo }}</p>
    <p> ステータス：{{ form.priority }}</p>
    <p>開始：{{ form.start_date }}</p>
    <p>終了：{{ form.end_date }}</p>
    <!--{{ form.as_p }}-->
    <input type="submit" value="create">
</form>
　

templates/calendar_app/delete.html
<form action = '' method = 'POST'>{% csrf_token %}
    {{ form.as_p }}
    
    <input type="submit" value="削除する">
    
</form>

templates/calendar_app/detail.html
<!DOCTYPE html>
<html>
<head></head>
<body>
    <h2>タイトル{{ todomodel.title }}</h2>
    <p>詳細：{{ todomodel.memo }}</p>
    <p>ステータス：{{ todomodel.get_priority_display }}</p>
    <p>開始：{{ todomodel.start_date }}</p>
    <p>終了：{{ todomodel.end_date }}</p>
    <a href="{% url 'cal:update' pk=todomodel.pk %}">編集</a>
    <a href="{% url 'cal:calendar'%}">戻る</a>
</body>
</html>

templates/calendar_app/list.html
<h1>A</h1>
{% for item in items %}
{{ item.title }}
{{ item.list }}

{% endfor %}

templates/calendar_app/update.html
<form action = '' method = 'POST'>
    {% csrf_token %}
    <p>タイトル：{{ form.title }}</p>
    <p>詳細：</p>
    <p>{{ form.memo }}</p>
    <p> ステータス：{{ form.priority }}</p>
    <p>開始：{{ form.start_date }}</p>
    <p>終了：{{ form.end_date }}</p>
    <input type="submit" value="更新">
    
</form>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyDiaryApp</title>
</head>
<body>
<h1>Diary App by Django</h1>
</body>
</html>